/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'wms',
    'functional',
    {
        type: 'category',
        label: 'Руководство пользователя',
        items: [
            'manual/manual',
        ],
    },
    {
        type: 'category',
        label: 'Руководство по работе с ТСД',
        items: [
            'tsd/tsd',
        ],
    },
    {
        type: 'category',
        label: 'Руководство администратора',
        items: [
            'admin/admin',
        ],
    },

  ],
};

export default sidebars;
